# Generated by Django 3.1.5 on 2021-01-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='text',
            field=models.CharField(default='', max_length=280),
        ),
        migrations.AddField(
            model_name='tweet',
            name='user_id',
            field=models.CharField(default='', max_length=280),
        ),
    ]
