# Generated by Django 3.1.5 on 2021-01-27 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapp', '0002_account_userfollowing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='followerCount',
        ),
        migrations.RemoveField(
            model_name='account',
            name='followingCount',
        ),
        migrations.RemoveField(
            model_name='account',
            name='profile_image',
        ),
    ]
