# Generated by Django 3.1.5 on 2021-01-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapp', '0003_auto_20210127_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='followerCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='followingCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
