# Generated by Django 3.1.5 on 2021-01-27 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapp', '0003_auto_20210128_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitterapp.account'),
        ),
    ]
