# Generated by Django 3.1.5 on 2021-01-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapp', '0004_auto_20210127_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='followerCount',
        ),
        migrations.RemoveField(
            model_name='account',
            name='followingCount',
        ),
        migrations.AddField(
            model_name='account',
            name='bio',
            field=models.CharField(default='', max_length=280),
        ),
        migrations.AddField(
            model_name='account',
            name='birthdate',
            field=models.DateTimeField(null=True),
        ),
    ]
