# Generated by Django 3.1.5 on 2021-01-27 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapp', '0005_auto_20210128_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='user_id',
        ),
        migrations.AddField(
            model_name='like',
            name='tweet_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='twitterapp.tweet'),
            preserve_default=False,
        ),
    ]
