# Generated by Django 3.1.5 on 2021-01-27 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapp', '0009_tweet_original_tweet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='original_tweet',
        ),
        migrations.AddField(
            model_name='tweet',
            name='original_tweet_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='original_tweet', to='twitterapp.tweet'),
            preserve_default=False,
        ),
    ]
