# Generated by Django 3.1.5 on 2021-01-27 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapp', '0010_auto_20210128_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='original_tweet_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='original_tweet', to='twitterapp.tweet'),
        ),
    ]
