# Generated by Django 3.1.5 on 2021-01-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapp', '0011_auto_20210128_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='dir',
            field=models.CharField(default='Avatar', max_length=280),
        ),
    ]
