# Generated by Django 3.1.5 on 2021-01-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapp', '0011_auto_20210128_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='original_tweet_id',
            field=models.IntegerField(default=0),
        ),
    ]
