# Generated by Django 3.1.5 on 2021-01-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapp', '0012_auto_20210128_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='original_tweet_id',
            field=models.IntegerField(default=1),
        ),
    ]
