# Generated by Django 3.1.5 on 2021-01-28 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapp', '0013_auto_20210128_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='user_id',
            new_name='user',
        ),
    ]
