# Generated by Django 3.1.5 on 2021-01-28 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapp', '0014_auto_20210128_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='user',
            new_name='user_id',
        ),
    ]
