# Generated by Django 3.1.5 on 2021-01-28 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapp', '0015_auto_20210128_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='twitterapp.image'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tweet', to='twitterapp.image'),
        ),
    ]
