# Generated by Django 3.1.5 on 2021-01-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapp', '0017_auto_20210128_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
