# Generated by Django 3.1.5 on 2021-01-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapp', '0018_auto_20210128_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='hashtag',
        ),
        migrations.AddField(
            model_name='tweet',
            name='hashtag',
            field=models.ManyToManyField(blank=True, related_name='tweets', to='twitterapp.Tweet'),
        ),
    ]
